import "./globals.css";
import { Sarabun } from "next/font/google";

const sarabun = Sarabun({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={sarabun.className}>{children}</body>
    </html>
  );
}
